spring.application.name=mercado
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Permite que Hibernate cree las tablas automáticamente al arrancar
spring.jpa.hibernate.ddl-auto=update

# Configura Spring Boot para que ejecute el archivo data.sql después de Hibernate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG
# Swagger UI disponible en /swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.packages-to-scan=com.surixapp.mercado.controller

JWT.SECRET=${JWT_SECRET}
JWT.EXPIRATION=${JWT_EXPIRATION}